python/cbl_vmm.py: Avoid type confusion around cores
cores needs to be an integer for QEMU but it needs to also be a string
for subprocess.run():

qemu-system-x86_64: Parameter 'smp.cpus' expects integer

TypeError: expected str, bytes or os.PathLike object, not int

Make memory an integer as well, purely for aesthetic reasons.

Signed-off-by: Nathan Chancellor <nathan@kernel.org>